import subprocess
proc = subprocess.Popen('cmd.exe', stdin=subprocess.PIPE)
proc.stdin.write(b"cd ..\n")
proc.stdin.write(b"cd ..\n")
proc.stdin.write(b"cd ..\n")
proc.stdin.write(b"cd ..\n")
proc.stdin.write(b"cd ..\n")
proc.stdin.write(b"cd ..\n")
proc.stdin.write(b"cd D:\programming\projects\JobAnalitics\JobAnalitics\n")
proc.stdin.write(b"cd env\n")
proc.stdin.write(b"cd scripts\n")
proc.stdin.write(b"activate.bat\n")
proc.stdin.write(b"cd ..\n")
proc.stdin.write(b"cd ..\n")
proc.stdin.write(b"python jobanalitics.py\n")
proc.stdin.close()
proc.wait()
