import subprocess
for i in range(1000):
    new_window_command = "cmd.exe /c start".split()
    proc = subprocess.Popen('cmd.exe', stdin=subprocess.PIPE)
    subprocess.check_call(new_window_command + ['python env.py'])
    # proc.stdin.write(b"cd ..\n")
    # proc.stdin.write(b"cd ..\n")
    # proc.stdin.write(b"cd ..\n")
    # proc.stdin.write(b"cd ..\n")
    # proc.stdin.write(b"cd ..\n")
    # proc.stdin.write(b"cd ..\n")
    # proc.stdin.write(b"cd ..\n")
    # proc.stdin.write(b"cd ..\n")
    # proc.stdin.write(b"cd ..\n")
    # proc.stdin.write(b"cd D:\programming\projects\JobAnalitics\JobAnalitics\n")
    # proc.stdin.write(b"cd env\n")
    # proc.stdin.write(b"cd scripts\n")
    # proc.stdin.write(b"activate.bat\n")
    # proc.stdin.write(b"cd ..\n")
    # proc.stdin.write(b"python jobanalitics.py\n")
    # proc.stdin.close()
    # proc.wait()
